name: fako_store
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  gap: ^3.0.1
  google_fonts: ^6.1.0
  sizer: ^2.0.15
  timeline_tile: ^2.0.0
  video_player: ^2.8.1
  chewie: ^1.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/rond.png
    - assets/images/min.png
    - assets/images/fond1.jpg
    - assets/images/fond2.jpg
    - assets/images/commande.png
    - assets/images/medoc.png
    - assets/icons/
    - assets/videos/video.mp4